MVCBlogSite/Controllers/AdminMakaleController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using MVCBlogSite.Models;
using PagedList;
using PagedList.Mvc;
namespace MVCBlogSite.Controllers
{
    public class AdminMakaleController : Controller
    {
        mvcblogDB dB = new mvcblogDB();
        // GET: AdminMakale
        public ActionResult Index(int Page=1)
        {
            var makales = dB.Makales.OrderByDescending(m=>m.MakaleId).ToPagedList(Page, 10);
            return View(makales);
        }

        // GET: AdminMakale/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: AdminMakale/Create
        public ActionResult Create()
        {
            ViewBag.KategoriId = new SelectList(dB.Kategoris,"KategoriId","KategoriAdi"); //viewbag ile kategori id'yi kategoris'ten çektik.
            return View();
        }

        // POST: AdminMakale/Create
        [HttpPost]
        public ActionResult Create(Makale makale,string etiketler,HttpPostedFileBase Foto)
        {
            if (ModelState.IsValid)
            {
                if (Foto != null)
                {
                    WebImage img = new WebImage(Foto.InputStream);
                    FileInfo fotoinfo = new FileInfo(Foto.FileName);

                    string newfoto = Guid.NewGuid().ToString() + fotoinfo.Extension;
                    img.Resize(800, 350);
                    img.Save("~/Uploads/MakaleFoto/" + newfoto);
                    makale.Foto = "~/Uploads/MakaleFoto/" + newfoto; //resmin yolunu veritabanında tuttuk kendisini klasöre yükledik.
                    

                }
                if (etiketler != null)
                {
                    string[] etiketdizi = etiketler.Split(',');
                    foreach (var i in etiketdizi)
                    {
                        var yenietiket = new Etiket { EtiketAdi = i };
                        dB.Etikets.Add(yenietiket);
                        makale.Etikets.Add(yenietiket);
                    }
                }
                makale.UyeId = Convert.ToInt32(Session["uyeid"]);
                makale.Okunma = 1;
                dB.Makales.Add(makale);
                dB.SaveChanges();
                dB.SaveChanges();
                return RedirectToAction("Index");
            }
                
                return View(makale);
            
        }

        // GET: AdminMakale/Edit/5
        public ActionResult Edit(int id)
        {
            var makale = dB.Makales.Where(m=>m.MakaleId==id).SingleOrDefault();
            if (makale==null)
            {
                return HttpNotFound();
            }
            ViewBag.KategoriId = new SelectList(dB.Kategoris, "KategoriId", "KategoriAdi",makale.KategoriId);
            return View(makale);
        }

        // POST: AdminMakale/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, HttpPostedFileBase Foto, Makale makale)
        {
            try
            {
                var makales = dB.Makales.Where(m => m.MakaleId == id).SingleOrDefault();
                if (Foto!=null)
                {
                    if (System.IO.File.Exists(Server.MapPath(makales.Foto)))
                    {
                        System.IO.File.Delete(Server.MapPath(makales.Foto));
                    }
                    WebImage img = new WebImage(Foto.InputStream);
                    FileInfo fotoinfo = new FileInfo(Foto.FileName);

                    string newfoto = Guid.NewGuid().ToString() + fotoinfo.Extension;
                    img.Resize(800, 350);
                    img.Save("~/Uploads/MakaleFoto/" + newfoto );
                    makales.Foto = "~/Uploads/MakaleFoto/" + newfoto;
                    makales.Baslik = makale.Baslik;
                    makales.Icerik = makale.Icerik;
                    makales.KategoriId = makale.KategoriId;
                    dB.SaveChanges();
                    return RedirectToAction("Index");
                }

                return View();
                
            }
            catch
            {
                ViewBag.KategoriId = new SelectList(dB.Kategoris, "KategoriId", "KategoriAdi", makale.KategoriId);

                return View();
            }
        }

        // GET: AdminMakale/Delete/5
        public ActionResult Delete(int id)
        {
            var makale = dB.Makales.Where(m => m.MakaleId == id).SingleOrDefault();
            if (makale==null)
            {
                return HttpNotFound();
            }
            return View(makale);
        }

        // POST: AdminMakale/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection Collections)
        {
            try
            {
                var makales = dB.Makales.Where(m => m.MakaleId == id).SingleOrDefault();
                if (makales == null)
                {
                    return HttpNotFound();
                }
                if (System.IO.File.Exists(Server.MapPath(makales.Foto)))
                {
                    System.IO.File.Delete(Server.MapPath(makales.Foto));
                }
                foreach (var i in makales.Yorums.ToList())
                {
                    dB.Yorums.Remove(i);
                }
                foreach (var i in makales.Etikets.ToList())
                {
                    dB.Etikets.Remove(i);
                }
                dB.Makales.Remove(makales);
                dB.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

MVCBlogSite/Views/AdminMakale/Create.cshtml
@model MVCBlogSite.Models.Makale

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<div class="col-md-8">
    <br />
    <h2>Makale Oluştur</h2>

    @using (Html.BeginForm("Create", "AdminMakale", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken() //güvenlik için otomatk oluşturuldu.

        <div class="form-horizontal">
            <br />
            <h4>Makale</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                @Html.LabelFor(model => model.KategoriId, "KategoriId", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("KategoriId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.KategoriId, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Baslik, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Baslik, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Baslik, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Icerik, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Icerik, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Icerik, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Foto, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input type="file" name="Foto" id="Foto" value="" accept=".jpg,.png,.gif,.JPEG,.jpeg" class="form-control" />
                    @Html.ValidationMessageFor(model => model.Foto, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Tarih, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Tarih, new { htmlAttributes = new { @class = "form-control", @type = "date" } })
                    @Html.ValidationMessageFor(model => model.Tarih, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.Label("Etiketler", new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBox("Etiketler")
                </div>
            </div>




            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Kaydet" class="btn btn-secondary" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Geri Dön", "Index")
    </div>
</div>

MVCBlogSite/Views/AdminMakale/Delete.cshtml
@model MVCBlogSite.Models.Makale

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<div class="col-md-8">
    <br />
    <h2>Silme</h2>
    <br />
    <h4>Silmek istediğine emin misin?</h4>
    <div>
        
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Kategori.KategoriAdi)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Kategori.KategoriAdi)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Baslik)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Baslik)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Icerik)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Icerik)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Foto)
            </dt>

            <dd>
                <img src="@Url.Content(@Model.Foto)" width="150" alt="Alternate Text" />
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Tarih)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Tarih)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.UyeId)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.UyeId)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Okunma)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Okunma)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Sil" class="btn btn-secondary" /> |
                @Html.ActionLink("Geri Dön", "Index")
            </div>
        }
    </div>
</div>

MVCBlogSite/Views/AdminMakale/Edit.cshtml
@model MVCBlogSite.Models.Makale

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<div class="col-md-8">
    <br />
    <h2>Düzenle</h2>

    @using (Html.BeginForm("Edit", "AdminMakale", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Makale Düzenle</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.MakaleId)

            <div class="form-group">
                @Html.LabelFor(model => model.Baslik, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Baslik, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Baslik, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Icerik, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Icerik, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Icerik, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Foto, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input type="file" name="Foto" id="Foto" accept=".jpg,.png,.gif,.JPEG,.jpeg" class="form-control" />
                    @Html.ValidationMessageFor(model => model.Foto, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.Label("Eski Foto", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <img width="75" src="@Url.Content(@Model.Foto)" alt="Alternate Text" />
                    @Html.ValidationMessageFor(model => model.Foto, "", new { @class = "text-danger" })
                </div>
            </div>


            <div class="form-group">
                @Html.LabelFor(model => model.Tarih, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Tarih, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Tarih, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.KategoriId, "KategoriId", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("KategoriId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.KategoriId, "", new { @class = "text-danger" })
                </div>
            </div>





            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Kaydet" class="btn btn-secondary" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Geri Dön", "Index")
    </div>
</div>

MVCBlogSite/Views/AdminMakale/Index.cshtml
@model IPagedList<MVCBlogSite.Models.Makale>
@using PagedList
@using PagedList.Mvc
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<div class="col-md-8">
    <br />
    <h2>Makaleler</h2>

    <p>
        @Html.ActionLink("Yeni Makale", "Create")
    </p>
</div>
    <table class="table">

        <tr>
            <th>
                @Html.Label("Kategori Adı")
            </th>
            <th>
                @Html.Label("Başlık")
            </th>

            <th>
                @Html.Label("Foto")
            </th>
            <th>
                @Html.Label("Tarih")
            </th>
            <th>
                @Html.Label("Okunma")
            </th>

            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Kategori.KategoriAdi)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Baslik)
                </td>

                <td>
                    <img class="rounded" width="75" src="@Url.Content(@item.Foto)" />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Tarih)
                </td>
                
                <td>
                    @Html.DisplayFor(modelItem => item.Okunma)
                </td>
                <td>
                    @Html.ActionLink("Düzenle", "Edit", new { id = item.MakaleId }) | @Html.ActionLink("Detaylar", "Details", new { id = item.MakaleId }) | @Html.ActionLink("Sil", "Delete", new { id = item.MakaleId })


                </td>
            </tr>
        }

    </table>


<div class="row">
    <div class="col-md-8 text-center">
        <div class="pagedList pagination">
            @Html.PagedListPager(Model, Page => Url.Action("Index", new { Page }), PagedList.Mvc.PagedListRenderOptions.Classic)
        </div>




    </div>


</div>